// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
       return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdRbayZlAwYGgFsNHAwzLukzFxZtnIZ9Q',
    appId: '1:802296915253:android:e8c39c19cea6cdc904987c',
    messagingSenderId: '802296915253',
    projectId: 'login-ferreteria',
    storageBucket: 'login-ferreteria.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0B8D5ytWfBNKAQoaxdCg0ma1PFEqOA18',
    appId: '1:802296915253:web:f6b6a2265d73aef304987c',
    messagingSenderId: '802296915253',
    projectId: 'login-ferreteria',
    authDomain: 'login-ferreteria.firebaseapp.com',
    storageBucket: 'login-ferreteria.firebasestorage.app',
    measurementId: 'G-WJQPS2C0YC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRT-9sTeo_e4QSqsFGTfhwtWw4GwAUEKI',
    appId: '1:802296915253:ios:57f1c2560cb60a0504987c',
    messagingSenderId: '802296915253',
    projectId: 'login-ferreteria',
    storageBucket: 'login-ferreteria.firebasestorage.app',
    iosBundleId: 'com.example.ferremateriales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRT-9sTeo_e4QSqsFGTfhwtWw4GwAUEKI',
    appId: '1:802296915253:ios:57f1c2560cb60a0504987c',
    messagingSenderId: '802296915253',
    projectId: 'login-ferreteria',
    storageBucket: 'login-ferreteria.firebasestorage.app',
    iosBundleId: 'com.example.ferremateriales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0B8D5ytWfBNKAQoaxdCg0ma1PFEqOA18',
    appId: '1:802296915253:web:e4b2aefde5cfded304987c',
    messagingSenderId: '802296915253',
    projectId: 'login-ferreteria',
    authDomain: 'login-ferreteria.firebaseapp.com',
    storageBucket: 'login-ferreteria.firebasestorage.app',
    measurementId: 'G-3NGBTE9RF4',
  );
}
